### ISSUE TITLE
看这个 相似的实现.gohls

### ISSUE THREAD

**Issue by wxf4150** [One2r/FetchM3u8#1]
https://github.com/kz26/gohls/blob/master/main.go
上面代码里的 这种 把hls 的ts文件列表.  append 模式写入一个文件.
和你的ffmeg concat 把 ts文件 联接, 有啥区别?
感觉gohls的更简单.

**Comment by One2r** [comment]
只是合并视频的不同方式而已，我是解析了.m3u8文件后，使用多个协程将视频下载下来后，然后用ffmeg将多个视频片段合并成一个视频文件，他的实现是根据.m3u8视频片段的顺序进行一个一个下载，下载一个就用io.Copy写到一个文件末尾去。

**Comment by One2r** [comment]
从代码上看，他的是简单些，依赖少些。但是我是为了将视频能够更快的下载下来，所以才用ffmeg最后合并的。

**Comment by wxf4150** [comment]
gohls 合并的应该不能播放.   你的ffmeg合并的,应该可以播放.
